env:
  TERM: alacritty
window:
  title: alacritty
  padding:
    x: 12
    y: 10
  dynamic_padding: true
  decorations: none
font:
  normal:
    family: RobotoMono Nerd Font Mono
    style: Regular, Bold
  size: 5.5
  hinting: true
  antialias: lcdv
  offset:
    x: 0
    y: 2
cursor:
  style: Block
  unfocused_hollow: true
draw_bold_text_with_bright_colors: true
background_opacity: .95
colors:
  primary:
    background:	'#000000'
    foreground:	'#e0e0d0'
  normal:
    black:	'#000000'
    red:	'#af5f00'
    green:	'#5faf5f'
    yellow:	'#d7af00'
    blue:	'#5fafff'
    magenta:	'#af5fd7'
    cyan:	'#008cac'
    white:	'#e0e0d0'
  bright:
    black:	'#95A5A6'
    red:	'#af5f00'
    green:	'#5faf5f'
    yellow:	'#d7af00'
    blue:	'#5fafff'
    magenta:	'#af5fd7'
    cyan:	'#00afd7'
    white:	'#ECF0F1'
  vi_mode_cursor:
    text: CellBackground
    cursor: '#00CC22'
key_bindings:
  - { key: Q,                               mode: Vi,          action: ToggleViMode            }
  - { key: K,        mods: Control|Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  - { key: J,        mods: Control|Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Return,   mods: Control|Shift,                      action: SpawnNewInstance }
