#!/bin/sh

xrandr --output eDP-1 --mode 1920x1080 --auto
xsetroot -cursor_name left_ptr &
xset r rate 300 60
xset s off
xset s noblank
xset -dpms
setxkbmap -option "caps:super"

feh --bg-scale /home/pape
redshift -l 43:-89 -t 6100k:3000k &
sh $HOME/.bin/bar.sh &

while true; do
  picom -GCb --config /dev/null \
    --vsync \
    --experimental-backends \
    --unredir-if-possible
  xinput set-button-map $(xinput list | grep -F "Logitech G203 Prodigy Gaming Mouse  " | awk '{print $8}' | cut -c 4-) 1 2 3 5 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
  dwm 2> ~/.dwm.log
done
