#!/bin/sh

[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

xrandr --output eDP-1 --mode 1920x1080 --auto
xsetroot -cursor_name left_ptr &
xset r rate 300 60
xset s off
xset s noblank
# xset -dpms
setxkbmap -option "caps:super"

feh --bg-scale /home/pape
redshift -l 43:-89 -t 5900k:2800k &
sh $HOME/.bin/bar.sh &
clipmenud &
amixer set Master 40% unmute

while true; do
  picom -GCb --config /dev/null \
    --vsync \
    --backend glx \
    --unredir-if-possible \
    --sw-opti 
  dwm
done
