#!/bin/bash
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

xrandr --output eDP --mode 1920x1080 --auto --set TearFree on
xsetroot -cursor_name left_ptr &
xset s off
xset s noblank
xset b off
xset b 0 0 0
xinput --set-prop 14 "libinput Accel Speed" .25
xinput disable "ELAN Touchscreen"
echo 0 > /sys/class/leds/platform::mute/brightness
echo 0 > /sys/class/leds/platform::micmute/brightness
# xset -dpms

ps -a | grep redshift || redshift -l 43:-89 -t 6000k:3500k &
sh $HOME/.bin/bar.sh &
amixer set Master 40% unmute
xmodmap $HOME/.xmodmap
xss-lock xtrlock &

while true; do
  xset r rate 300 60
  autorandr --change
  feh --bg-scale /home/pape
  picom --vsync --experimental-backends -GCb --config /dev/null &
  killall sxhkd; sxhkd &
  dwm
done
