#!/bin/bash

last=$(date +%s%3N)
trigger_last () {
    now=$(date +%s%3N)
    echo "click: "$(( now - last ))"ms"
    last=$(date +%s%3N)
}

#KNIGHT
if (( $(pgrep -a click | wc -l) <= 2)); then
    r=$[ $RANDOM % 56 + 1238 ]
    count=1
    for i in $(seq 1 $r); do
        d=$[ $RANDOM % 466 + 811 ]
        # echo $i $d
        if [ $count -gt 20 ]; then
            echo "F2"
            echo "sleep: "$d"ms"
            sleep "${d}e-3"
            xdotool key F2 && \
            xdotool click --repeat 1 --delay $((d / 2)) 1 && \
            trigger_last
            s=$((d + 300 / 2))
            echo "sleep: "$s"ms"
            sleep "${s}e-3"
            echo "F2"
            xdotool key F2 && \
            count=1
        fi
        if ! (( d % 100 )); then 
            s=$((RANDOM / 1500))
            echo "sleep: ${s}"
            sleep $s
        fi
        if ! (( d % 6 )); then
            d=$((d / 2))
        fi
        if ! (( d % 8 )); then
            xdotool click --repeat 1 --delay $(( d * 10 / count )) 1
            count=$((count+1))
            trigger_last
        fi
        if ! (( d % 75 )); then
            x=9.6
            echo "sleep:"$x
            sleep $x
        fi
        xdotool click --repeat 1 --delay $d 1
        trigger_last
        count=$((count+1))
    done
else
    killall click
fi

# NMZ
 # if (( $(pgrep -a click | wc -l) <= 2)); then
 #     r=$[ $RANDOM % 28 + 238 ]
 #     for i in $(seq 1 $r); do
 #         sleep 0.$[ $RANDOM % 55 ]
 #         xdotool click --repeat 1 1
 #         sleep 0.$[ $RANDOM % 55 ]
 #         xdotool click --repeat 1 1
 #         sleep $[ $RANDOM % 10 + 40 ]
 #     done
 # else
 #     killall click
 # fi
