#!/bin/bash
#script for docking laptop, disables keyboard and touchpad and sets up
#monitor/workspace flow
#passing -u will undo this

#array of internal devices to float
declare -a devices=("Elan Touchpad" "AT Translated Set 2 keyboard")
declare -a masters=(2 3)
undo=0

while [ -n "$1" ]; do
    case "$1" in
    -u) echo "-u option passed" ;undo=1;;
     *) echo "option not recognized" ;;
    esac

    shift
done
for ((i=0; i<${#devices[@]}; ++i)) ; do
    if [ $undo -eq 1 ]; then
        xinput reattach $(eval "xinput list | grep \"${devices[i]}\" | cut -d '=' -f2 | cut -d '[' -f1 | tr -d -c '0-9'") ${masters[i]}
    else
        xinput float $(eval "xinput list | grep \"${devices[i]}\" | cut -d '=' -f2 | cut -d '[' -f1 | tr -d -c '0-9'")
    fi
done
