#!/bin/bash
setxkbmap -option "caps:super"
if [[ $(cat /proc/acpi/button/lid/LID/state | grep open) == "" ]] && \
    (( $(xrandr --query | grep " connected" | wc -l) > 1 )); then
    echo "disable eDP"
    xrandr --output eDP --off
else
    echo "enable eDP"
    xrandr --output eDP --auto
fi
exit 0
