#!/bin/bash
setxkbmap -option "caps:super"
if [[ $(cat /proc/acpi/button/lid/LID/state | grep open) == "" ]]; then
    echo "disable eDP"
    xrandr --output eDP-1 --off
else
    echo "enable eDP"
    xrandr --output eDP-1 --auto
fi
exit 0
