#!/usr/bin/env bash
gap=2
panel=26
export gap
export panel

bspc config top_padding $(($panel-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

bspc config window_gap $gap

#Various settings
bspc config gapless_monocle     true
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#source wal colors
. "/home/e/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$background"
bspc config active_border_color "$background"
bspc config focused_border_color "$color7"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$foreground"

bspc config border_width 0

bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus button2 #middle click
bspc config swallow_first_click true

#Settings for manual splitting
bspc config split_ratio         0.50

bspc monitor eDP1 -d i ii iii iv v vi vii viii ix x

###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

bspc rule -a spotify state=pseudo_tiled
bspc rule -a firefox state=tiled
bspc rule -a runelite state=floating

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode

sh ~/.config/polybar/launch.sh
