#!/usr/bin/env bash
gap=1
panel=26
export gap
export panel

bspc config top_padding $(($panel-$gap))
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config window_gap 0

#Various settings
bspc config gapless_monocle     true
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#source wal colors
. "/home/e/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "#4A4A4A"
bspc config active_border_color "$background"
bspc config focused_border_color "#AAAAAA"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$foreground"

bspc config border_width 1

bspc config focus_follows_pointer false
bspc config pointer_follows_focus true
bspc config click_to_focus button1 
bspc config swallow_first_click false

#Settings for manual splitting
bspc config split_ratio         0.50

bspc monitor eDP-1 -d 1 2 3 4 5 6 7

sh ~/.config/bspwm/autostart
